// src/components/index/index.vue
<template>
  <div>
    <m-header/>
    <banner :topList="topList"></banner>
  </div>
</template>

<script type="text/ecmascript-6">
  import Banner from 'common/banner/banner'
  import MHeader from 'common/m-header/m-header'
  import {getLatest} from 'api/index'

  export default {
    name: 'index',
    data() {
      return {
        topList: []
      }
    },
    created() {
      this._getLatest()
    },
    methods: {
      _getLatest() {
        getLatest()
        .then((response) => {
          this.topList = response.top_stories
        })
        .catch((error) => {
          console.error('内部错误，错误原因: ' + error)
        })
      }
    },
    components: {
      Banner,
      MHeader
    }
  }
</script>

<style scoped lang="stylus" rel="stylesheet/stylus">

</style>

// src/components/index/index.jsx
import React, {Component} from 'react';
import {getLatest} from 'api/index';
import MHeader from "common/m-header/m-header";
import Banner from "common/banner/banner";

class Index extends Component {
  // banner 上的热门
  topList = [];

  componentWillMount() {
    getLatest()
      .then((response) => {
        this.topList = response.top_stories;
        console.log(this.topList)
      })
      .catch((error) => {
        console.error('内部错误，错误原因: ' + error);
      })
  }

  render() {
    return (
      <div>
        <MHeader title='首页'/>
        <Banner />
      </div>
    );
  }
}

export default Index;
